### ISSUE TITLE
Career Support - Resumes - Build your resume

### ISSUE THREAD

**Issue by NickRyanWeber** [NickRyanWeber/assignments#30]
# Key areas of Information to include:

## Contact information
- [x] Email
- [x] Phone Number (Google numbers are great if you want to protect your personal number)
- [x] Github link
- [ ] Portfolio link

## Summary
- [x] Should be a brief paragraph (three to five sentences) that shows the value you bring by highlighting your skills and a couple of big career wins. But rather than labeling it a “summary,” use a headline that encapsulates your credentials.

## Skills
- [x] You’ll want to incorporate the right keywords, optimize your resume for applicant tracking systems

## Professional experience
- [x] Focus on your accomplishments rather than your day-to-day responsibilities
Education
- [x] Write where you went college and your degree.
- [ ] It’s ok to move this towards the top if you have limited work experience and want to highlight your experience at SDG

## Bonus:
- [x] Volunteering and community service

## Due Date: Wednesday, September 25th
 - [ ] Upload or submit a link to your resume for review.

**Comment by NickRyanWeber** [comment]
[NicholasRyanWeberResume2019.pdf](https://github.com/NickRyanWeber/assignments/files/3624234/NicholasRyanWeberResume2019.pdf)

**Comment by NickRyanWeber** [comment]
I made another one...I kinda like this one better
[NicholasRyanWeberResume2019 v2.0.pdf](https://github.com/NickRyanWeber/assignments/files/3624402/NicholasRyanWeberResume2019.v2.0.pdf)

**Comment by ktrammell95** [comment]
Cut out that weird empty page
Look to see if you can make your links clickable when viewing on a computer

Other than those you worked really hard on it and it shows, excellent resume
